import { expect, test } from "@playwright/test";
import { readCinematicStory } from "./cinematic-story-controls";

test("guided story follows earned actions, pauses aftermath, and resumes without replay", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/?accessible=1", { waitUntil: "domcontentloaded" });
  await page.bringToFront();
  await expect(page.locator(".onboarding-gate")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("button", { name: "Begin", exact: true }).click();
  const guide = page.locator('[data-guided-story="broken-floor.confession"]');
  await expect(guide).toBeVisible();
  await expect(guide).toHaveAttribute("data-guided-event", "broken-floor.first-wipe");
  await expect(guide).not.toContainText("cage");
  await page.locator('[data-accessible-witness="fragment-001"]').click();
  await page.locator('button[data-story-event-id="broken-floor.first-wipe"]').click();
  await expect(guide).toHaveAttribute("data-guided-response", "true");
  await expect(guide).toContainText("A clear patch opens in the water.");
  await expect(guide).toHaveAttribute("data-guided-event", "broken-floor.forest-revealed");
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(page.locator("#experience-settings-dialog")).toBeVisible();
  await page.waitForTimeout(3900);
  await page.keyboard.press("Escape");
  await expect(guide).toHaveAttribute("data-guided-response", "true");
  // Presentation time requires the caption to be in view, not scrolled offscreen.
  await guide.scrollIntoViewIfNeeded();
  await expect(guide).toHaveAttribute("data-guided-response", "false", { timeout: 8000 });
  await page.locator('button[data-story-event-id="broken-floor.forest-revealed"]').click();
  await expect(guide).toHaveAttribute("data-guided-event", "broken-floor.inversion");
  await expect(guide).toContainText("The branches were beneath you all along.");
  const path = testInfo.outputPath("guided-story-aftermath.png");
  await guide.scrollIntoViewIfNeeded();
  await page.screenshot({ path });
  await testInfo.attach("guided-story-aftermath", { path, contentType: "image/png" });
  const earned = (await readCinematicStory(page)).completedStoryEventIds;
  await page.reload({ waitUntil: "domcontentloaded" });
  await expect(page.locator(".onboarding-gate")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("button", { name: "Continue the Journey", exact: true }).click();
  await expect(guide).toHaveAttribute("data-guided-response", "false");
  await expect(guide).toHaveAttribute("data-guided-event", "broken-floor.inversion");
  expect((await readCinematicStory(page)).completedStoryEventIds).toEqual(earned);
  await page.locator('button[data-story-event-id="broken-floor.inversion"]').click();
  await expect(guide).toHaveAttribute("data-guided-beat", "complete");
  await guide.scrollIntoViewIfNeeded();
  await guide.getByRole("button", { name: "Follow the next path", exact: true }).click();
  const arrival = page.locator('[data-guided-story="enchanted.rabbit-hole"]');
  await expect(arrival).toBeVisible();
  await expect(arrival).toContainText("Follow the distant lantern.");
  await arrival.getByRole("button", { name: "What do I do?", exact: true }).click();
  await expect(arrival).toContainText("It waits for you");
  await arrival.getByRole("button", { name: "Hide story guidance", exact: true }).click();
  await expect(arrival.getByRole("button", { name: "Show story guidance", exact: true })).toBeVisible();
  await arrival.getByRole("button", { name: "Show story guidance", exact: true }).click();
  await expect(arrival).toContainText("Follow the distant lantern.");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await expect(page.locator("canvas, vite-error-overlay")).toHaveCount(0);
  expect(errors).toEqual([]);
});

test("players can hold turning points without losing the next accepted consequence", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/?accessible=1", { waitUntil: "domcontentloaded" });
  await page.bringToFront();
  await expect(page.locator(".onboarding-gate")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("button", { name: "Begin", exact: true }).click();
  const guide = page.locator('[data-guided-story="broken-floor.confession"]');
  await expect(guide).toBeVisible();
  await page.locator('[data-accessible-witness="fragment-001"]').click();
  await page.locator('button[data-story-event-id="broken-floor.first-wipe"]').click();
  await guide.getByRole("button", { name: "Stay with this moment", exact: true }).click();
  await expect(guide).toHaveAttribute("data-aftermath-held", "true");
  // Gameplay remains available while the player holds a presentation moment.
  await page.locator('button[data-story-event-id="broken-floor.forest-revealed"]').click();
  await expect(guide).toHaveAttribute("data-guided-event", "broken-floor.inversion");
  await expect(guide).toHaveAttribute("data-aftermath-event", "broken-floor.first-wipe");
  await page.waitForTimeout(4100);
  await expect(guide).toContainText("A clear patch opens in the water.");
  const earned = (await readCinematicStory(page)).completedStoryEventIds;
  await guide.getByRole("button", { name: "Continue past this moment", exact: true }).click();
  await expect(guide).toHaveAttribute("data-aftermath-event", "broken-floor.forest-revealed");
  await expect(guide).toHaveAttribute("data-aftermath-held", "false");
  expect((await readCinematicStory(page)).completedStoryEventIds).toEqual(earned);
  // Hiding guidance cannot consume an unread caption offscreen.
  await guide.getByRole("button", { name: "Hide story guidance", exact: true }).click();
  await page.waitForTimeout(4100);
  await guide.getByRole("button", { name: "Show story guidance", exact: true }).click();
  await expect(guide).toContainText("The branches were beneath you all along.");
  await guide.getByRole("button", { name: "Stay with this moment", exact: true }).click();
  await guide.scrollIntoViewIfNeeded();
  const path = testInfo.outputPath("held-earned-aftermath.png");
  await page.screenshot({ path });
  await testInfo.attach("held-earned-aftermath", { path, contentType: "image/png" });
  await guide.getByRole("button", { name: "Continue past this moment", exact: true }).click();
  await expect(guide).toHaveAttribute("data-guided-response", "false");
  expect((await readCinematicStory(page)).completedStoryEventIds).toEqual(earned);
  await page.reload({ waitUntil: "domcontentloaded" });
  await expect(page.locator(".onboarding-gate")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("button", { name: "Continue the Journey", exact: true }).click();
  await expect(guide).toHaveAttribute("data-guided-response", "false");
  await expect(guide).toHaveAttribute("data-aftermath-held", "false");
  expect((await readCinematicStory(page)).completedStoryEventIds).toEqual(earned);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});

test("the next-step view preserves the emotional moment and keyboard context", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/?accessible=1", { waitUntil: "domcontentloaded" });
  await page.bringToFront();
  await expect(page.locator(".onboarding-gate")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("button", { name: "Begin", exact: true }).click();
  const guide = page.locator('[data-guided-story="broken-floor.confession"]');
  await page.locator('[data-accessible-witness="fragment-001"]').click();
  await page.locator('button[data-story-event-id="broken-floor.first-wipe"]').click();
  await guide.scrollIntoViewIfNeeded();
  await guide.getByRole("button", { name: "Continue past this moment", exact: true }).focus();
  await page.waitForTimeout(4100);
  await expect(guide).toHaveAttribute("data-aftermath-event", "broken-floor.first-wipe");
  await expect(guide.getByRole("button", { name: "Continue past this moment", exact: true })).toBeFocused();
  const before = (await readCinematicStory(page)).completedStoryEventIds;
  await guide.getByRole("button", { name: "Show my next step", exact: true }).click();
  const step = guide.getByRole("region", { name: "Your current next step", exact: true });
  await expect(step).toBeVisible();
  await expect(step).toContainText("Wipe again.");
  expect((await readCinematicStory(page)).completedStoryEventIds).toEqual(before);
  await page.locator('button[data-story-event-id="broken-floor.forest-revealed"]').click();
  await expect(step).toContainText("Touch the forest in the reflection.");
  await expect(step).not.toContainText("cage");
  await page.waitForTimeout(4100);
  await expect(guide).toHaveAttribute("data-aftermath-event", "broken-floor.first-wipe");
  await guide.scrollIntoViewIfNeeded();
  const path = testInfo.outputPath("next-step-without-losing-the-moment.png");
  await page.screenshot({ path });
  await testInfo.attach("next-step-without-losing-the-moment", { path, contentType: "image/png" });
  await guide.getByRole("button", { name: "Return to this moment", exact: true }).click();
  await guide.getByRole("button", { name: "Continue past this moment", exact: true }).click();
  await expect(guide).toHaveAttribute("data-aftermath-event", "broken-floor.forest-revealed");
  await expect(guide.locator(".guided-story__intention")).toBeFocused();
  const earned = (await readCinematicStory(page)).completedStoryEventIds;
  await page.getByRole("button", { name: "Settings", exact: true }).focus();
  // The accessible journey owns scrolling; the viewport-height document does
  // not scroll in every engine. Exercise the same panel a reader scrolls.
  await page.locator(".accessible-story-journey").evaluate(element => element.scrollTo({ top: element.scrollHeight, behavior: "instant" }));
  await expect(guide.locator(".guided-story__intention")).not.toBeInViewport();
  await expect(guide).toHaveAttribute("data-aftermath-readable", "false");
  await page.waitForTimeout(4100);
  await expect(guide).toHaveAttribute("data-aftermath-event", "broken-floor.forest-revealed");
  await guide.scrollIntoViewIfNeeded();
  await expect(guide).toHaveAttribute("data-aftermath-readable", "true");
  await expect(guide).toHaveAttribute("data-guided-response", "false", { timeout: 8000 });
  expect((await readCinematicStory(page)).completedStoryEventIds).toEqual(earned);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});

test("enlarged guidance controls keep their click target when focused", async ({ page }) => {
  test.setTimeout(90_000);
  await page.setViewportSize({ width: 320, height: 568 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/?accessible=1", { waitUntil: "domcontentloaded" });
  await page.bringToFront();
  await expect(page.locator(".onboarding-gate")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("button", { name: "Begin", exact: true }).click();
  await page.addStyleTag({ content: "html { font-size: 24px; }" });
  await page.locator('[data-accessible-witness="fragment-001"]').click();
  await page.locator('button[data-story-event-id="broken-floor.first-wipe"]').click();
  const guide = page.locator('[data-guided-story="broken-floor.confession"]');
  const button = guide.getByRole("button", { name: "Show my next step", exact: true });
  await button.scrollIntoViewIfNeeded();
  const before = await button.boundingBox();
  await button.focus();
  const after = await button.boundingBox();
  expect(before).not.toBeNull();
  expect(after).not.toBeNull();
  expect(Math.abs(after!.y - before!.y)).toBeLessThan(1);
  await button.click();
  await expect(guide.getByRole("region", { name: "Your current next step" })).toBeVisible();
  await expect(guide).toHaveAttribute("data-aftermath-event", "broken-floor.first-wipe");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});
